### PR TITLE
Drop the “Feature Policy integration” section

### PR DESCRIPTION
**Pull request by sideshowbarker**
See https://github.com/whatwg/xhr/pull/321 and https://github.com/whatwg/xhr/pull/295

***
<a href="https://whatpr.org/xhr/322.html" title="Last updated on Mar 26, 2021, 8:16 AM UTC (ec82fb3)">Preview</a> | <a href="https://whatpr.org/xhr/322/82ff852...ec82fb3.html" title="Last updated on Mar 26, 2021, 8:16 AM UTC (ec82fb3)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
Thanks, you'll also need to remove the instance of sync-xhr elsewhere.

**Comment by sideshowbarker** [comment]
> Thanks, you'll also need to remove the instance of sync-xhr elsewhere.

That’s in https://github.com/w3c/webappsec-permissions-policy/blob/ab4fa82727f370307117e61d170ca9a2f21dc29b/index.bs#L1126-L1128

So, I’ll raise a PR against the Permissions Policy spec to drop or change that.

But note also, the Permissions Policy has an example with this:
```
   const new_frame = document.createElement('iframe');
   new_frame.allow = 'sync-xhr';
   // This will be true, as the iframe is allowed to use sync-xhr at whatever URL is
   // mentioned in its src attribute, even though that attribute is not yet set.
   const is_sync_xhr_allowed = new_frame.featurePolicy.allowsFeature('sync-xhr');
```
https://w3c.github.io/webappsec-permissions-policy/#example-92e8a40f

So, I guess I’ll need replace that example with something else. Suggestion welcome.

**Comment by annevk** [comment]
I didn't mean that, sorry, I meant the step in https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send (which is why the build is failing). But if you want to take the other bits on as well, sounds good to me. 😊

A good example of a Permissions Policy would be `camera` or `geolocation`.

**Comment by sideshowbarker** [comment]
> I didn't mean that, sorry, I meant the step in [xhr.spec.whatwg.org/#dom-xmlhttprequest-send](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send) (which is why the build is failing).

ah OK — pushed a commit to drop that step

> But if you want to take the other bits on as well, sounds good to me. 😊
> 
> A good example of a Permissions Policy would be `camera` or `geolocation`.

Thanks — I’ll raise a PR against the Permissions Policy spec to change the example/reference there to one of those

**Comment by sideshowbarker** [comment]
For the `sync-xhr` references in the Permissions Policy spec, I just raised an issue  https://github.com/w3c/webappsec-permissions-policy/issues/419

**Comment by annevk** [comment]
@sideshowbarker thanks! It seems this needs an update to MDN as well as it currently references XHR for this?

**Comment by annevk** [comment]
Ah, that was resolved by https://github.com/mdn/browser-compat-data/commit/bcc150faf0fbaa2a54f87cb0e60e5a2d85e0a1ed.

**Review by annevk — APPROVED** [review]

**Comment by sideshowbarker** [comment]
> Ah, that was resolved by [mdn/browser-compat-data@bcc150f](https://github.com/mdn/browser-compat-data/commit/bcc150faf0fbaa2a54f87cb0e60e5a2d85e0a1ed).

Yeah but actually there are some other changes we can make to MDN; I’ll raise a PR there too

**Comment by sideshowbarker** [comment]
https://github.com/mdn/content/pull/3529 is the update to the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/sync-xhr article

**Pull request merged**
