### PR TITLE
Expose ProgressEvent to ServiceWorker

### LINKED ISSUE #305: Expose ProgressEvent to ServiceWorker
FileReader is exposed to ServiceWorker and uses ProgressEvent, but the event interface is not exposed to ServiceWorker since 9d0a9bb85c32e10788227a79943362bede178a7c.

Exposing it to ServiceWorker also matches Gecko and WebKit implementation:

* Gecko https://searchfox.org/mozilla-central/rev/2aea8e093c3c6d10bc3f385e0ea66b6387221e71/dom/webidl/ProgressEvent.webidl
* WebKit https://webkit-search.igalia.com/webkit/rev/7418d7c94bd380d0844789d128e5805e28d9c572/Source/WebCore/dom/ProgressEvent.idl

### PR DESCRIPTION
**Pull request by Rashika101**
Fixes  #305 
"Expose ProgressEvent to ServiceWorker"

- [x] At least two implementers are interested (and none opposed):
   * "Gecko"
   * "WebKit"
- [ ] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
   * …
- [ ] [Implementation bugs](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) are filed:
   * Chrome: …
   * Firefox: …
   * Safari: …

(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)

***
<a href="https://whatpr.org/xhr/308.html" title="Last updated on Jan 26, 2021, 11:51 AM UTC (f0580b0)">Preview</a> | <a href="https://whatpr.org/xhr/308/b7726ee...f0580b0.html" title="Last updated on Jan 26, 2021, 11:51 AM UTC (f0580b0)">Diff</a>

### CODE REVIEW

**Comment by saschanaz** [comment]
Hey, thanks, the patch looks perfect! A few nits for the description, could you:

* Modify the title to "Expose ProgressEvent to ServiceWorker" to show the intention of this patch?
* Remove a space in `[x ]` so that it can be `[x]`. You'll see it magically becoming a checkbox!
* Add `Fixes #305` at the top line. Doing so will show this patch in the issue so that other's won't duplicate your work 😉

**Comment by Rashika101** [comment]
Is that okay?
Yes,The checkbox has been created..
But in 1st point title modification what is that?Isn't similar?

**Comment by saschanaz** [comment]
You'll see the Edit button next to the Open with button, please click it and you can edit the title 😊

**Comment by saschanaz** [comment]
BTW, you need to sign the Participation Agreement for your contribution, please go [here](https://participate.whatwg.org/agreement) do the required steps. Sorry for the unexpected paperwork 😬

**Comment by saschanaz** [comment]
After that, during workdays someone will review this once more and merge it. Thank you for your hard work 😍

**Comment by Rashika101** [comment]
Thank you
@saschanaz Modified the title!!
Explain a little more on participation agreement ,what are the steps i need to take in that agreement...
When I am submitting ,"Invalid entity name name " is coming..

**Comment by saschanaz** [comment]
Entity name? I think you are supposed to fill only the "If signing as an Individual" form 👀 (unless you are doing this as a part of your job).

**Comment by saschanaz** [comment]
And thank you for setting the right title! It would be even better without the quotes.

**Comment by Rashika101** [comment]
Thank You @saschanaz 
Quotes removed...
Signed the Participation agreement.
When my PR will merge?
and still my participation showing pending..

**Comment by saschanaz** [comment]
Per [this page](https://participate.whatwg.org/agreement-status?user=Rashika101&repo=xhr) it needs to be verified by the admins, which will happen probably next week. Hold tight 😉

**Review by annevk — COMMENTED** [review]
Thanks! Could you change this to `Window,Worker` instead? `Worker` is a shorthand for all three and we generally use that when applicable.

**Comment by annevk** [comment]
Also, you should feel free to add your name to the Acknowledgments section.

**Comment by Rashika101** [comment]
@annevk 
Is there any changes i have to make?

**Comment by Rashika101** [comment]
@saschanaz Thank You for your guidance!!
Is there any thing else that i have to do?

**Comment by annevk** [comment]
@Rashika101 yeah, instead of `Window,DedicatedWorker,SharedWorker,ServiceWorker` you want `Window,Worker`. And you can also add your name to the Acknowledgments section at the bottom of the document if you wish.

**Comment by saschanaz** [comment]
To reduce confusion: `Worker` is a shorter equivalent of `DedicatedWorker,SharedWorker,ServiceWorker`. We want to make the code short as possible to make it more manageable, and thus `[Window,Worker]` is preferred here. Sorry for confusing you 🙏

Feel free to ping me when you need any more help 💕

**Comment by Rashika101** [comment]
@saschanaz @annevk 
I did the changes as per your guidance. A new patch and pull request has been created...
Did I had done it correctly? Please recheck it.
Thanks!

**Comment by saschanaz** [comment]
Hmm, you don't have to create new patch, you can edit existing patch by Files Changed -> "..." button -> Edit File. But that also works 👀

**Comment by Rashika101** [comment]
Should I do it again now in this patch?
As you say...

**Comment by saschanaz** [comment]
I'd say please give it a try 😁

**Comment by Rashika101** [comment]
Done.....Is that visible?

**Comment by saschanaz** [comment]
Yup, perfectly splendid!

**Comment by Rashika101** [comment]
Thank You...Any change required in title?

**Comment by saschanaz** [comment]
No, the patch still does the same work, just in a shorter way 😀

BTW, have you considered adding your name to Acknowledgments? We totally want to list the contributors who gave valuable patch(es) and you also deserve it! It's not a requirement, so feel free to ignore it.

**Comment by Rashika101** [comment]
Yes, i want to add name...How to do that?

**Comment by saschanaz** [comment]
It's same, in the same file search "Acknowledgments" and you'll see several names ordered in alphabetical way. Please add your name there 😉

**Comment by Rashika101** [comment]
Excuse me.....feeling stupid
Didn't get acknowledgement...

**Comment by saschanaz** [comment]
Oh my fault, it's "Acknowledgments" (it lacks "e" between "legd" and "ments")

**Comment by Rashika101** [comment]
Sorry.....
Where do I search it?

**Comment by saschanaz** [comment]
In the xhr.bs file, the one you just edited. Make sure you tap Control+F (Or Command+F if you are on macOS) inside the text editor or you won't see anything.

**Comment by saschanaz** [comment]
Oh I mean,

1. Files changed -> "..." button (next to xhr.bs) -> Edit file
2. Search "Ackno"
3. Add your name, in the alphabetical order 😉

**Comment by Rashika101** [comment]
I did it in the same way. But nothing happens.

**Comment by saschanaz** [comment]
Could you explain what you saw on the screen when you tried it? Did you fail to find the names?

**Comment by Rashika101** [comment]
When I search "Ackno" nothing comes up..

**Comment by saschanaz** [comment]
Did you click the text editor before searching? It works in a bit weird way, it may not come up if you didn't.

(It's sad that we couldn't ship FindText API to make this straightforward.)

**Comment by Rashika101** [comment]
Is there any other way to do so?
I am trying but nothing happens.

**Comment by saschanaz** [comment]
Hmm, alternatively you can just scroll down to line number 1911 (the number you see at the left of the text editor) and it's there.

image

**Comment by Rashika101** [comment]
Oh,Thank You so much.
I did it.
Anything else i need to do.

**Comment by saschanaz** [comment]
Good! Could you move your name before Robin Berjon so that the list can be alphabetically ordered? (so that Rashika comes before Robin)

**Comment by Rashika101** [comment]
Oh excuse me.
Done.

**Comment by saschanaz** [comment]
Okay, now everything is perfect and we can just wait for the verification for your participation form. Thank you! 🎉🎉

**Comment by Rashika101** [comment]
Thank you. Until we can work on other issues.?

**Comment by saschanaz** [comment]
I guess no good first issue anymore in this repository. I think issues in whatwg generally require some knowledge of web standards than others (this one was luckily exceptional 😁) , so you may want to try other repositories too. @annevk may have some thought, though.

**Review by annevk — APPROVED** [review]
Thanks! I looked through some of the remaining good first issues within the WHATWG and it seems they require a bit more experience indeed.

**Pull request merged**
