### PR TITLE
Convert XHR to bikeshed

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
Need to fix somehow: the test script.

@tabatkins I get `FATAL ERROR: Multiple local 'argument' <dfn>s for 'FormData/append(name, value)' have the same linking text 'name'.` probably due to `append()` being an overloaded method. Any thoughts on how to fix that?

**Comment by annevk** [comment]
@tabatkins I also get duplicate ID warnings I cannot figure out. (Maybe in part because nothing is generating yet.)

**Comment by tabatkins** [comment]
> probably due to append() being an overloaded method. 

Yup, that's the problem here.  Bikeshed uses argument names, not types, in its signatures, so if you have overloads that use the same name and have the same shape, it'll be a problem. (This has the same shape because, to help with human usability, it registers variants that omit the optional args too, so the Blob overload has both a 3-arg and 2-arg version, and the 2-arg looks exactly like the USVString overload.)

I'm not 100% sure how I would fix this on the Bikeshed side; it might not really be possible without adding some new concepts to allow disambiguation.  Easy to fix on the source side by just using a different argument name for one of the required args (presumably the second arg, as it's the one that varies).

> I also get duplicate ID warnings I cannot figure out. (Maybe in part because nothing is generating yet.)

Remember you can force-generate with `bikeshed -f spec`! That way you can see what the output is and figure out what's going wrong.  In this case, the issue is that you have a bunch of things like:

```
The
<dfn lt="dom XMLHttpRequest upload"><code>upload</code></dfn>
attribute
```
(line 724-726)

which *attempt* to define the upload attribute of XMLHttpRequest, but aren't marked up properly to do so, and which happen to generate the exact same automatic ID as the dfn in the WebIDL block.

**Comment by annevk** [comment]
I also get the duplicate ID error for
```
<dfn id=dom-xmlhttprequest-open method for=XMLHttpRequest><code>open(<var>method</var>, <var>url</var>, <var>async</var>, <var>username</var>, <var>password</var>)</code></dfn>
```
which I can remove by removing the explicit ID, but it seems rather weird I don't get to set my own ID there (even if it were the same).

**Comment by annevk** [comment]
@tabatkins hi again. I made substantial progress I think. Apart from the `FormData` issues, I now have these:
```
LINK ERROR: Multiple possible 'dfn' refs for 'origin'.
Arbitrarily chose the one in url.
If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
spec:url; type:dfn; text:origin
spec:html; type:dfn; for:/; text:origin
spec:html; type:dfn; for:environment settings object; text:origin
spec:fetch; type:dfn; text:origin
spec:dom; type:dfn; text:origin
```
As far as I can tell I only reference "origin" twice and both times I do so in an unambiguous manner that has worked before.
```
LINK ERROR: Multiple possible 'idl' local refs for 'timeout'.
Arbitrarily chose the one with type 'attribute' and for 'XMLHttpRequest'.
```
I'm not sure where this is coming from as all usage of `timeout` is appropriately qualified.
```
LINK ERROR: Multiple possible 'dfn' refs for 'fetch'.
Arbitrarily chose the one in fetch.
If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
spec:fetch; type:dfn; for:fetch record; text:fetch
spec:fetch; type:dfn; for:/; text:fetch
```
All usage of the term "fetch" and "fetching" is marked up with `for=/` so I don't understand where this is coming from either.

I checked all of these several times. Would appreciate help. (I can't use -l debugging as that does not seem to work together with -f.)

**Comment by tabatkins** [comment]
Running `bikeshed -f spec -l` to get the line numbers makes these a lot easier to debug. ^_^

The "origin" link is on line 171 - you're linking to the Origin http header.

---

The "timeout" link is a bit harder, as it's a Bikeshed-generated element and thus doesn't have a line number yet. However, you can tell what it's looking for with `bikeshed refs --status=local --text=timeout --for=XMLHttpRequest` - it reveals that you have both an *attribute* named `timeout` and an *event* named `timeout`, both for XMLHttpRequest.  These are both IDL types, so the bare `{{XMLHttpRequest/timeout}}` can't distinguish them; you have to clarify the type you want like `{{XMLHttpRequest/timeout!!attribute}}`.

I need to make this error message a lot better; it's hard to debug.

---

For "fetch", you want line 889. I just pushed a change so that, when the line number can't be found, it'll at least print the element's outerHTML. You probably missed this because you're using case-sensitive regex, and this is a sentence-starting `<a>Fetch</a>`.

**Comment by annevk** [comment]
Thanks, why are events IDL types?

**Comment by annevk** [comment]
Okay, apart from the HTML references, `open()`, and `FormData`'s `append()` and `set()`, this is done.

This ends up fixing #98 so I should mention that in the commit message.

**Comment by tabatkins** [comment]
Events are IDL types because they get scoped to other IDL types, and it seemed appropriate at the time. ¯\_(ツ)_/¯

**Comment by annevk** [comment]
@tabatkins when I applied the following (does not fix all outstanding problems, I know) I got "`FATAL ERROR: Multiple local 'method' <dfn>s for 'FormData' have the same linking text 'append(name, blobValue, filename)'.`" What now? This seemed to be exactly what you suggested I do.
```diff
diff --git a/xhr.bs b/xhr.bs
index f847c7b..43b4cb4 100644
--- a/xhr.bs
+++ b/xhr.bs
@@ -1875,7 +1875,7 @@ typedef (File or USVString) FormDataEntryValue;
  Exposed=(Window,Worker)]
 interface FormData {
   void append(USVString name, USVString value);
-  void append(USVString name, Blob value, optional USVString filename);
+  void append(USVString name, Blob blobValue, optional USVString filename);
   void delete(USVString name);
   FormDataEntryValue? get(USVString name);
   sequence&lt;FormDataEntryValue> getAll(USVString name);
@@ -1946,10 +1946,14 @@ constructor must run these steps:
 </ol>
 
 <p>The
-<dfn id=dom-formdata-append method for=FormData><code>append(<var>name</var>, <var>value</var>, <var>filename</var>)</code></dfn>
-method, when invoked, must run these steps:
+<dfn id=dom-formdata-append method for=FormData><code>append(<var>name</var>, <var>value</var>)</code></dfn>
+and
+<dfn id=dom-formdata-append-blob method for=FormData><code>append(<var>name</var>, <var>blobValue</var>, <var>filename</var>)</code></dfn>
+methods, when invoked, must run these steps:
 
 <ol>
+ <li><p>Let <var>value</var> be <var>value</var> if given, and <var>blobValue</var> otherwise.
+
  <li><p>Let <var>entry</var> be the result of <a lt="create an entry">creating an entry</a>
  with <var>name</var>, <var>value</var>, and <var>filename</var> if given.
 
@@ -1957,6 +1961,9 @@ method, when invoked, must run these steps:
  <a>entries</a>.
 </ol>
 
+<p class=note>The reason there is an argument named <var>value</var> as well as <var>blobValue</var>
+is due to a limitation of the editing software used to write the XMLHttpRequest Standard.
+
 <p>The
 <dfn id=dom-formdata-delete method for=FormData><code>delete(<var>name</var>)</code></dfn>
 method, when invoked, must remove all <a>entries</a>
```

**Comment by tabatkins** [comment]
This confused me a ton too, so I discussed it with @plinss and we figured it out - it's due to a weakness in widlparser currently.  He's going to add/fix the functionality I need, and then this will work correctly.

**Comment by annevk** [comment]
So it sounds like there's no specification yet using Bikeshed that has overloads. If that's the case and since we're generally moving away from them, can't we just have nice things instead of the above patch?

**Comment by tabatkins** [comment]
Feel free to move away from overloads; that's nice. ^_^

But no, as I said multiple times before, dramatically changing the linking model for methods would be a large amount of work.

Making this work proper, on the other hand, improves method handling in general, and also happens to make linking to overloads work well.

**Comment by annevk** [comment]
It would only change for overloaded methods, no? And those don't work anyway at the moment.

**Comment by tabatkins** [comment]
No, it happens to fix some other variations on prose method definitions that weren't being successfully captured before.

**Comment by plinss** [comment]
widlparser has been updated for this: plinss/widlparser@fbb10e96658e5494b1ac0daddbaa8c8203b3f0b3

**Comment by annevk** [comment]
So now we're putting a flaw of Bikeshed into widlparser? Shouldn't widlparser use types per IDL?

**Comment by tabatkins** [comment]
No, this is a querying function used by Bikeshed to get all the associated signatures of a method from a single signature.

Drop it, bro. The behavior isn't a flaw, it's how people naturally refer to things.  It's how *you yourself* actually refer to functions in your spec - you refer to the functions in prose with their arg names, not their arg types.  I don't know why you're so bothered by this, but it's not going to change, because it's the obviously correct way to handle natural human prose.

**Comment by annevk** [comment]
I'm bothered by it because it's not technically correct and it forces standards to be written in a way that implementations are not. That mismatch is wrong.

**Comment by tabatkins** [comment]
As we discussed before, *overloads* are already "written in a way that implementations are not".  If you want to match impls more closely, write a single method; that avoids all the issues, but requires you to duplicate some of the IDL machinery in your prose.

There's nothing technically incorrect here. There's nothing *wrong* with having overloads use different arg names.  It's merely less elegant, in your opinion.  On the other hand, it matches better with how people usually want to refer to things in prose.

**Comment by domenic** [comment]
That's not true; implementations use C++ overloads of the type the spec used to be able to.

**Comment by tabatkins** [comment]
And there's nothing preventing them from using different argnames in their C++ overloads, either.  Bikeshed is opinionated on this case to match how people prefer to write prose; it locks out certain behaviors that are technically allowed by other systems but that would complicate the layers Bikeshed builds on top of it.

**Pull request merged**
