### PR TITLE
Editorial: add an IDL index

### PR DESCRIPTION
**Pull request by domenic**
Not sure if you want to add the terms index too, but I was looking for the IDL index and noticed it was missing, so here's a drive-by fix.

### CODE REVIEW

**Comment by annevk** [comment]
Do we want to converge this across standards? If so, I guess we should add the index.

**Comment by domenic** [comment]
I'd say yes. Maybe we should decide on the index though at the same time?

**Comment by annevk** [comment]
Yeah, both indexes. Do you want to change it? Maybe also add .editorconfig and .gitattributes while you're there? (Migrating to the decentralized deploy is blocked on multiple files at the moment.)

**Comment by domenic** [comment]
Not really, sorry, this was just a drive-by edit from the GitHub web interface :). We can leave it for later I guess.

**Comment by annevk** [comment]
You can review / merge (with a new commit message) my changes then.

**Comment by domenic** [comment]
LGTM :)

**Pull request merged**
