### PR TITLE
Fix typo in FormData idl

### PR DESCRIPTION
**Pull request by takenspc**

### CODE REVIEW

**Comment by annevk** [comment]
Thank you for your pull request! However, you patched `Overview.html` rather than `Overview.src.html`. `Overview.html` is a generated file so I cannot use this patch. Would you like to change it to patch `Overview.src.html` instead? (If not, I can make the changes myself, I'll still give you credit for finding it of course.)

**Comment by takenspc** [comment]
Oops. I patched Overview.src.html.
I'm not sure whether commits should be squashed or not. If so, please let me know.

**Comment by annevk** [comment]
Yeah, please squash/rebase commits.

**Comment by takenspc** [comment]
Thanks. I squashed commits

**Comment by annevk** [comment]
Thank you!

**Pull request closed without merging**
