### PR TITLE
Add a <dfn> for FormData's entry's type.

### PR DESCRIPTION
**Pull request by mikewest**
I'd like to link to this from other specs.

WDYT, @annevk ?

### CODE REVIEW

**Comment by annevk** [comment]
How do you plan on using this?

At some point I should really tighten the integration with HTML here...

**Comment by mikewest** [comment]
Step 9.2.1 of https://w3c.github.io/webappsec-credential-management/#passwordcredential-form-constructor (which I think I copy/pasted from HTML somewhere?).

**Comment by mikewest** [comment]
Sorry, I didn't copy it. I'm misremembering an earlier draft where I was mildly forking https://html.spec.whatwg.org/multipage/forms.html#constructing-form-data-set.

**Comment by annevk** [comment]
You could just check that value is a string. That whole thing seems very hackish though and not really primitive-inspired...

**Comment by mikewest** [comment]
*shrug* You know that bit better than I do. I'd be happy to have a cleaner way to turn a FormData into a URLSearchParams (or to allow urlencoded serialization of the one so that I didn't need to do the conversion in the first place). As-is, this seems like the set of materials I have to work with, so...

**Comment by annevk** [comment]
Agreed on _shrug_ 😊. I'm not entirely sure what to do here given that my colleagues are less than enthused by the credentials specification. So I could put effort in it, but at the moment there doesn't seem much likelihood of success.

As for this change, it seems you could also check the type of the value, right? Or is there something I'm missing?

**Comment by mikewest** [comment]
Abandoning this. :)

**Pull request closed without merging**
